# Generated by Django 6.0.4 on 2026-06-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlibrary_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlibrary_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('cover_i', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_ids', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('first_publish_date', models.DateField(blank=True, null=True, verbose_name='First publish year')),
                ('description', models.TextField(null=True)),
                ('excerpt', models.TextField(null=True)),
                ('was_requested_detail', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('avg_rating', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('authors', models.ManyToManyField(to='books.author', verbose_name='authors')),
                ('subjects', models.ManyToManyField(blank=True, related_name='books', to='books.subject')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'book',
            },
        ),
    ]
