# Generated by Django 6.0.4 on 2026-05-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='book',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
