# Generated by Django 6.0.4 on 2026-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='cover_ids',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='was_requested_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE author ALTER COLUMN birth_date TYPE date USING (birth_date::text || '-01-01')::date",
            reverse_sql='ALTER TABLE author ALTER COLUMN birth_date TYPE integer USING EXTRACT(YEAR FROM birth_date)::integer',
        ),
    ]
