# Generated by Django 6.0.4 on 2026-05-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_review_avg_rating_book_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_i',
            field=models.CharField(null=True),
        ),
    ]
