# Generated by Django 6.0.4 on 2026-06-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='known_as',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
