# Generated by Django 6.0.4 on 2026-05-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='openlibrary_key',
        ),
    ]
