# Generated by Django 6.0.4 on 2026-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_author_known_as_alter_author_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbns',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
