# Generated by Django 6.0.4 on 2026-07-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_isbns'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_openlibrary_page',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
