# Generated by Django 6.0.4 on 2026-05-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_author_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
