# Generated by Django 6.0.4 on 2026-07-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_subject_subject_openlibrary_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_openlibrary_page',
            new_name='openlibrary_page',
        ),
    ]
