# Generated by Django 6.0.4 on 2026-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_rename_subject_openlibrary_page_subject_openlibrary_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='openlibrary_page',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
