# Generated by Django 6.0.4 on 2026-05-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_publish_year',
            field=models.IntegerField(null=True, verbose_name='First publish year'),
        ),
    ]
