# Generated by Django 6.0.4 on 2026-05-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='emoji',
            field=models.CharField(null=True),
        ),
    ]
