# Generated by Django 6.0.4 on 2026-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_subject_emoji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='book',
            name='first_publish_year',
            field=models.CharField(blank=True, null=True, verbose_name='First publish year'),
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
