# Generated by Django 6.0.4 on 2026-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_review_options_alter_book_first_publish_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
