# Generated by Django 6.0.4 on 2026-06-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('books', '0018_remove_subject_emoji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.RunSQL("TRUNCATE TABLE book CASCADE;"),
        migrations.AddField(
            model_name='book',
            name='openlibrary_key',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_i',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
