# Generated by Django 6.0.4 on 2026-06-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_review_options_book_openlibrary_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='openlibrary_key',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
