# Generated by Django 6.0.4 on 2026-06-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_book_openlibrary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_i',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
