# Generated by Django 6.0.4 on 2026-06-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_book_cover_ids_book_description_alter_book_cover_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='excerpt',
            field=models.TextField(null=True),
        ),
    ]
