# Generated by Django 6.0.4 on 2026-06-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_book_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='first_publish_year',
            new_name='first_publish_date',
        ),
    ]
