# Generated by Django 6.0.4 on 2026-06-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_rename_first_publish_year_book_first_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='was_requested_detail',
            field=models.BooleanField(default=False),
        ),
    ]
