# Generated by Django 6.0.4 on 2026-06-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_book_was_requested_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
