# Generated by Django 6.0.4 on 2026-05-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
