# Generated by Django 6.0.4 on 2026-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='books_read',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='reading_now',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, verbose_name='First name'),
        ),
    ]
