# Generated by Django 6.0.4 on 2026-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recentactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='User image'),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('added', 'Added to library'), ('want_to_read', 'Want to Read'), ('reading', 'Started reading'), ('read', 'Finished reading'), ('rated', 'Rated'), ('change_rate', 'Change rating'), ('reviewed', 'Reviewed')], verbose_name='action'),
        ),
    ]
