# Generated by Django 6.0.4 on 2026-07-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_author_known_as_alter_author_full_name'),
        ('users', '0003_user_profile_image_alter_recentactivity_action'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recentactivity',
            index=models.Index(fields=['user', '-created_at'], name='users_activ_user_id_674d4c_idx'),
        ),
    ]
