# Generated by Django 6.0.4 on 2026-05-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_second_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='books_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reading_now',
            field=models.IntegerField(default=0),
        ),
    ]
