# Generated by Django 6.0.4 on 2026-07-03 17:45

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_recentactivity_users_activ_user_id_674d4c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=users.models.generate_short_uuid, editable=False, max_length=10, unique=True),
        ),
    ]
