# Generated by Django 6.0.4 on 2026-05-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avg_rating_alter_user_books_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='want_to_read',
            field=models.IntegerField(default=0),
        ),
    ]
