# Generated by Django 6.0.4 on 2026-07-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='library_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
