# Generated by Django 6.0.4 on 2026-05-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_want_to_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
