# Generated by Django 6.0.4 on 2026-06-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books_read',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reading_now',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='want_to_read',
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, verbose_name='Last name'),
        ),
    ]
