# Generated by Django 6.0.4 on 2026-07-09 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_library_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='library_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
