# Generated by Django 6.0.4 on 2026-07-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_library_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='library_updated_at',
            new_name='content_updated_at',
        ),
    ]
