SUBJECT_MAP = {
    'Science Fiction': [
        'science fiction',
        'science-fiction',
        'american science fiction',
        'fiction - science fiction',
        'fiction / science fiction / general',
        'fiction, science fiction, general',
        'fiction, science fiction, action & adventure',
        'science fiction - general',
        'science fiction & fantasy',
        'science fiction, fantasy, horror',
        'science fiction, fantasy, & magic',
    ],
    'Fantasy': [
        'fantasy',
        'fantasy fiction',
        'fantasy & magic',
        'english fantasy fiction',
        'juvenile fantasy fiction',
        'fiction, fantasy, general',
        'fiction, fantasy, epic',
        'fiction, fantasy, dragons & mythical creatures',
        'fiction, fairy tales, folk tales, legends & mythology',
        'magic',
        'magic in fiction',
        'witchcraft',
        'wizards',
        'dragons',
    ],
    'Horror': [
        'horror',
        'horror fiction',
        'horror stories',
        'horror tales',
        'fiction, horror',
        'fiction, gothic',
        'gothic literature',
        'vampires',
        'supernatural',
        'ghosts',
        'monsters',
    ],
    'Mystery & Detective': [
        'mystery',
        'mystery fiction',
        'mystery and detective stories',
        'detective fiction',
        'detective and mystery fiction',
        'detective and mystery stories',
        'crime',
        'crime novel',
        'crime & mystery fiction',
        'fiction, mystery & detective, general',
        'fiction, mystery & detective, traditional',
        'fiction, mystery & detective, historical',
        'private investigators',
        'murder',
        'locked-room mysteries',
    ],
    'Thriller & Suspense': [
        'thriller',
        'fiction, thrillers, general',
        'fiction, thrillers, suspense',
        'fiction, suspense',
        'mystery & suspense',
        'true crime / espionage',
    ],
    'Classics': [
        'classics',
        'classic fiction',
        'classic literature',
        'fiction classics',
        'literary',
        'literary fiction',
        'fiction, classics',
        'american literature',
        'english literature',
        'russian literature',
    ],
    'Historical Fiction': [
        'historical fiction',
        'fiction, historical',
        'fiction, historical, general',
        'history',
        'nineteen twenties',
        'great depression',
    ],
    'Romance': [
        'romance',
        'romance fiction',
        'love stories',
        'fiction, romance, general',
        'fiction, romance, historical, 20th century',
        'man-woman relationships',
        'first loves',
    ],
    'Adventure': [
        'adventure',
        'adventure stories',
        'action & adventure',
        'fiction, action & adventure',
        'quests (expeditions)',
    ],
    'Coming of Age': [
        'coming of age',
        'bildungsromans',
        'loss of innocence',
        'fiction, coming of age',
        'adolescence',
        'school stories',
    ],
    'Young Adult': [
        'young adult',
        'young adult fiction',
        'teen fiction',
        'juvenile fiction',
        'juvenile literature',
        'teen & young adult literature',
        'child and youth fiction',
    ],
    'Children': [
        "children's fiction",
        "children's stories",
        "children's books",
        "children's literature",
        'juvenile works',
    ],
    'Biography': [
        'biography',
        'biographies',
        'biography & autobiography',
        'biography & autobiography / business',
        'biography & autobiography / rich & famous',
        'businesspeople, biography',
    ],
    'Self-Help': [
        'self-help / personal growth / general.',
        'personal growth',
        'behavior modification',
        'habit',
        'habit breaking',
        'self-actualization (psychology)',
    ],
    'Business': [
        'business',
        'business & economics',
        'business & economics / general',
        'business & economics / industries / computer industry',
        'leadership',
        'management',
        'success in business',
    ],
    'Psychology': [
        'psychology',
        'psychology / social psychology',
        'psychological fiction',
        'fiction, psychological',
        'psychological aspects',
    ],
    'Science & Non-Fiction': [
        'science',
        'non-fiction',
        'nonfiction',
        'anthropology',
        'evolution',
        'civilization',
        'world history',
        'history',
        'technology and civilization',
        'life sciences',
    ],
    'Politics & Society': [
        'totalitarianism',
        'fiction, political',
        'race relations',
        'racial injustice',
        'racial segregation',
        'social conditions',
        'class differences',
        'american dream',
    ],
    'LGBTQ+': [
        'lgbt',
        'lgbtq coming out',
        'homosexuality',
        'coming out (sexual orientation)',
        'young adult fiction, lgbtq+',
    ],
}